In [9]:
import gensim
import gensim.downloader


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\HP\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\HP\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "c:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\HP\anaconda3\Lib\site-packages\tornado\

AttributeError: _ARRAY_API not found

ImportError: numpy.core.multiarray failed to import

In [10]:
python -m venv venv_gensim

SyntaxError: invalid syntax (3867816118.py, line 1)

In [7]:
! pip install numpy==1.24.4

   ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.8 MB 445.2 kB/s eta 0:00:34
   ---------------------------------------- 0.1/14.8 MB 550.5 kB/s eta 0:00:27
   ---------------------------------------- 0.1/14.8 MB 804.6 kB/s eta 0:00:19
    --------------------------------------- 0.3/14.8 MB 1.3 MB/s eta 0:00:12
   - -------------------------------------- 0.4/14.8 MB 1.7 MB/s eta 0:00:09
   - -------------------------------------- 0.5/14.8 MB 2.0 MB/s eta 0:00:08
   - -------------------------------------- 0.7/14.8 MB 2.1 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/14.8 MB 2.3 MB/s eta 0:00:06
   -- ------------------------------------- 0.9/14.8 MB 2.1 MB/s eta 0:00:07
   -- ------------------------------------- 0.9/14.8 MB 2.1 MB/s eta 0:00:07
   -- ------------------------------------- 0.9/14.8 MB 2.1 MB/s eta 0:00:07
   -- -

  You can safely remove it manually.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.24.4 which is incompatible.


In [1]:
gensim.downloader.info()["models"].keys()

NameError: name 'gensim' is not defined

In [8]:
word2vec_300 = gensim.downloader.load("word2vec-google-news-300")
# W2V model. Pretrained on part of Google news dataset. Each word/embedding is a 300 long vector

In [14]:
king = word2vec_300.get_vector("king")

In [17]:
word2vec_300.most_similar("king")

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [16]:
queen = word2vec_300.get_vector("queen")

In [21]:
word2vec_300.most_similar("queen")

[('queens', 0.739944338798523),
 ('princess', 0.7070532441139221),
 ('king', 0.6510956883430481),
 ('monarch', 0.6383602023124695),
 ('very_pampered_McElhatton', 0.6357026696205139),
 ('Queen', 0.6163407564163208),
 ('NYC_anglophiles_aflutter', 0.6060680150985718),
 ('Queen_Consort', 0.5923796892166138),
 ('princesses', 0.5908074975013733),
 ('royal', 0.5637185573577881)]

In [22]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(king.reshape(1,300), queen.reshape(1,300))

array([[0.6510957]], dtype=float32)

In [25]:
king = word2vec_300.get_vector("king")
queen = word2vec_300.get_vector("queen")
man = word2vec_300.get_vector("man")
woman = word2vec_300.get_vector("woman")

new_vec = king-man+woman 

cosine_similarity(new_vec.reshape(1,300), queen.reshape(1,300))

array([[0.7300518]], dtype=float32)

In [28]:
Italy = word2vec_300.get_vector("Italy")
Rome = word2vec_300.get_vector("Rome")
Japan = word2vec_300.get_vector("Japan")
Tokyo = word2vec_300.get_vector("Tokyo")

new_vec = Japan - Tokyo + Rome 

cosine_similarity(new_vec.reshape(1,300), Italy.reshape(1,300))

array([[0.6476528]], dtype=float32)

In [29]:
word2vec_300.most_similar("france")

[('spain', 0.6375302672386169),
 ('french', 0.6326055526733398),
 ('germany', 0.6314354538917542),
 ('europe', 0.6264256238937378),
 ('italy', 0.6257959008216858),
 ('england', 0.6120776534080505),
 ('european', 0.6074905395507812),
 ('belgium', 0.5972345471382141),
 ('usa', 0.5948355197906494),
 ('serbia', 0.5805614590644836)]

In [36]:
Sent1 = "Narendra Modi is addressing the media"
Sent2 = "Prime Minister is speaking to the press"

In [40]:
embed_1 = word2vec_300.get_mean_vector(Sent1.split())
embed_2 = word2vec_300.get_mean_vector(Sent2.split())

cosine_similarity(embed_1.reshape(1,300), embed_2.reshape(1,300))

array([[0.6136963]], dtype=float32)

### Training a Word2Vec Model

In [41]:
from nltk.corpus import brown

In [42]:
" ".join(brown.sents()[100])

'Daniel personally led the fight for the measure , which he had watered down considerably since its rejection by two previous Legislatures , in a public hearing before the House Committee on Revenue and Taxation .'

In [43]:
model = gensim.models.Word2Vec(brown.sents(), vector_size=20, epochs=10, window=10)

In [ ]:
model.wv.get_vector("King").shape

(20,)

In [49]:
model.wv.most_similar("King")

[('Richard', 0.8972120881080627),
 ('John', 0.8911973834037781),
 ('Charles', 0.8906499147415161),
 ('Judge', 0.8796738386154175),
 ('Powell', 0.8778663277626038),
 ('Marshall', 0.8773447871208191),
 ('Thompson', 0.8706364631652832),
 ('Martin', 0.8654319643974304),
 ('Sir', 0.8641459345817566),
 ('Ritter', 0.8616040945053101)]

#### Limitations of Word2Vec

In [ ]:
word2vec_300.get_vector("joebiden")

KeyError: "Key 'joebiden' not present"