In [2]:
%pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 24.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 50.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 14.0 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatib

In [1]:
import gensim
import gensim.downloader

In [2]:
gensim.downloader.info()["models"].keys()

dict_keys(['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis'])

In [3]:
word2vec_300 = gensim.downloader.load("word2vec-google-news-300")
# W2V model. Pretrained on part of Google news dataset. Each word/embedding is a 300 long vector

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [4]:
king = word2vec_300.get_vector("king")

In [5]:
word2vec_300.most_similar("king")

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [6]:
queen = word2vec_300.get_vector("queen")

In [7]:
word2vec_300.most_similar("queen")

[('queens', 0.739944338798523),
 ('princess', 0.7070532441139221),
 ('king', 0.6510956883430481),
 ('monarch', 0.6383602023124695),
 ('very_pampered_McElhatton', 0.6357026696205139),
 ('Queen', 0.6163407564163208),
 ('NYC_anglophiles_aflutter', 0.6060680150985718),
 ('Queen_Consort', 0.5923796892166138),
 ('princesses', 0.5908074975013733),
 ('royal', 0.5637185573577881)]

In [8]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(king.reshape(1,300), queen.reshape(1,300))

array([[0.6510957]], dtype=float32)

In [9]:
king = word2vec_300.get_vector("king")
queen = word2vec_300.get_vector("queen")
man = word2vec_300.get_vector("man")
woman = word2vec_300.get_vector("woman")

new_vec = king-man+woman

cosine_similarity(new_vec.reshape(1,300), queen.reshape(1,300))

array([[0.7300518]], dtype=float32)

In [10]:
Italy = word2vec_300.get_vector("Italy")
Rome = word2vec_300.get_vector("Rome")
Japan = word2vec_300.get_vector("Japan")
Tokyo = word2vec_300.get_vector("Tokyo")

new_vec = Japan - Tokyo + Rome

cosine_similarity(new_vec.reshape(1,300), Italy.reshape(1,300))

array([[0.6476528]], dtype=float32)

In [11]:
word2vec_300.most_similar("france")

[('spain', 0.6375302672386169),
 ('french', 0.6326055526733398),
 ('germany', 0.6314354538917542),
 ('europe', 0.6264256238937378),
 ('italy', 0.6257959008216858),
 ('england', 0.6120776534080505),
 ('european', 0.6074905395507812),
 ('belgium', 0.5972345471382141),
 ('usa', 0.5948355197906494),
 ('serbia', 0.5805614590644836)]

In [12]:
Sent1 = "Narendra Modi is addressing the media"
Sent2 = "Prime Minister is speaking to the press"

In [13]:
embed_1 = word2vec_300.get_mean_vector(Sent1.split())
embed_2 = word2vec_300.get_mean_vector(Sent2.split())

cosine_similarity(embed_1.reshape(1,300), embed_2.reshape(1,300))

array([[0.6136963]], dtype=float32)

### Training a Word2Vec Model

In [ ]:
from nltk.corpus import brown

In [16]:
import nltk
nltk.download('brown')

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.


True

In [17]:
" ".join(brown.sents()[100])

'Daniel personally led the fight for the measure , which he had watered down considerably since its rejection by two previous Legislatures , in a public hearing before the House Committee on Revenue and Taxation .'

In [19]:
model = gensim.models.Word2Vec(brown.sents(), vector_size=20, epochs=10, window=10)

In [20]:
model.wv.get_vector("King").shape

(20,)

In [21]:
model.wv.most_similar("King")

[('Richard', 0.8971058130264282),
 ('John', 0.891362190246582),
 ('Charles', 0.8903337717056274),
 ('Judge', 0.8796567916870117),
 ('Powell', 0.8780490159988403),
 ('Marshall', 0.8773132562637329),
 ('Thompson', 0.8707560300827026),
 ('Martin', 0.8653168082237244),
 ('Sir', 0.8636487722396851),
 ('Ritter', 0.8603838086128235)]

#### Limitations of Word2Vec

In [22]:
word2vec_300.get_vector("joebiden")

KeyError: "Key 'joebiden' not present"